### PR TITLE
refactor: update dependencies and change syntax details to support do…

### LINKED ISSUE #89: Upgrade to MDX and Docusaurus v3

### PR DESCRIPTION
**Pull request by YUUU23**
Update honeycomb docs to use Docusaurus 3.0
* update relative dependencies that Docusaurus 3.0 requires 
* change syntax details according to errors thrown when building 
   * sidebars: cannot have version paths appended to it 
   * `<default-value >` : < are taken as JSX in Docusaurus 3.0, so it needs to be wrapped with inline-code 
* extra spaces were deleted when updating automatically

### CODE REVIEW

**Comment by YUUU23** [comment]
Both test build failing because of broken links are fixed in this [issue](https://github.com/orgs/brown-ccv/projects/16/views/10?pane=issue&itemId=69989198) 
Perhaps one solution may be after we merge this [PR](https://github.com/brown-ccv/honeycomb-docs/pull/148) for the broken link issue and rebase this PR, the builds would pass (?)

**Comment by RobertGemmaJr** [comment]
Could you fix this line? It's in the quick_start - I would only worry about fixing it for the current version

image

**Review by RobertGemmaJr — CHANGES_REQUESTED** [review]
Just a small little fix that I saw from the JSX changes. I left a screenshot, I'd do one last sweep of everything but it's just about there!

**Comment by YUUU23** [comment]
> Just a small little fix that I saw from the JSX changes. I left a screenshot, I'd do one last sweep of everything but it's just about there! 

Should be fixed in the new commit! Thank you for catching this : ) I also did another run through for all the pages in the most recent version, and I think it looks good but let me know if you see anything else that needs to be changed!

**Review by RobertGemmaJr — APPROVED** [review]
Great! Everything looks perfect 🚀

**Pull request merged**
