### PR TITLE
remove: delete duplicate electron field in global install in quick_start

### LINKED ISSUE #140: Remove duplicate `electron` field in global install (quick start)

### PR DESCRIPTION
**Pull request by YUUU23**
* In `quick_start.mdx`, remove the duplicate electron field in the global install code instruction

### CODE REVIEW

**Review by RobertGemmaJr — COMMENTED** [review]
@YUUU23 Could you send a few screenshots of the quick start guide on your local host? It looks like you're formatter is changing a bunch of stuff. I don't think we have a linter setup for the project right now so that's okay, I just want to make sure everything still looks okay. Especially the tab items around line 175-200

**Comment by YUUU23** [comment]
@RobertGemmaJr  
Here are the screenshots of the Quick Start page on my local end (line 175-200 and the duplicated electron issue on this issue should be on page 3 of the screenshots): 
[PR142.pdf](https://github.com/user-attachments/files/15959890/PR142.pdf)

Let me know if I should change anything! Also, let me know if you think it's easier if I open a new branch and somehow make changes to that line only? 
Thank you!

**Comment by YUUU23** [comment]
Rebased this branch so that it now includes the firebase preview link

**Comment by RobertGemmaJr** [comment]
@YUUU23 Can you bring your local changes on `main` up to date, checkout this branch, and then do `git merge main`? It looks like this PR isn't recognizing the changes to Firebase in main

**Comment by YUUU23** [comment]
@RobertGemmaJr I just followed the directions provided and merged main with this branch. Please let me know if anything else needs to be changed.

**Review by RobertGemmaJr — APPROVED** [review]
Looks great! Thanks cleaning up that merge with main! 🚀

**Review by RobertGemmaJr — APPROVED** [review]

**Pull request merged**
